# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        loginservice:
            id: AppBundle\Security\User\WebserviceUserProvider
    encoders:
        AppBundle\Security\User\WebserviceUser:
            algorithm: bcrypt
        AppBundle\Entity\User:
            algorithm: bcrypt
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /user/security/login
                check_path: /user/security/login
                provider: loginservice
            logout:
                 path:   /user/security/logout
                 target: /

    access_control:
            #- { path: ^/user, roles: ROLE_USER }
            - { path: ^/user/security, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: /user/admin, roles: ROLE_ADMIN }